# Generated by Django 5.2.1 on 2025-05-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_amount_transaction_amout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expence', 'Expence'), ('Transfer', 'Transfer'), ('Investment', 'Investment'), ('Loan Payment', 'Loan Payment')], max_length=15),
        ),
    ]
